// src/lib/pdfExport.js
// Uses jsPDF + html2canvas to export today's task list as a clean PDF.
// The PDF is minimal/clean — white background, black text (not neon).

import jsPDF from 'jspdf';

/**
 * Formats minutes as "X hr Y min" or just "Y min"
 */
function formatDuration(minutes) {
  if (!minutes) return '0 min';
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  if (h === 0) return `${m} min`;
  if (m === 0) return `${h} hr`;
  return `${h} hr ${m} min`;
}

/**
 * Format a Date as a readable string
 */
function formatDate(date) {
  return date.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

/**
 * Export today's tasks to a clean PDF.
 * @param {Object} sections - { rolledOver, openTasks, events, dailyItems, weeklyItems, monthlyItems }
 */
export async function exportTodayToPDF(sections) {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;

  let y = margin;

  // --- Header ---
  pdf.setFontSize(22);
  pdf.setFont('helvetica', 'bold');
  pdf.text('COMMAND CENTER', margin, y);
  y += 8;

  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(80, 80, 80);
  pdf.text(formatDate(new Date()), margin, y);
  y += 4;

  // Divider
  pdf.setDrawColor(200, 200, 200);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 8;

  pdf.setTextColor(0, 0, 0);

  const addSection = (title, items, renderItem) => {
    if (!items || items.length === 0) return;

    // Check if we need a new page
    if (y > 260) {
      pdf.addPage();
      y = margin;
    }

    // Section title
    pdf.setFontSize(13);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(30, 30, 30);
    pdf.text(title.toUpperCase(), margin, y);
    y += 6;

    // Section underline
    pdf.setDrawColor(180, 180, 180);
    pdf.line(margin, y, pageWidth - margin, y);
    y += 5;

    items.forEach((item) => {
      if (y > 270) {
        pdf.addPage();
        y = margin;
      }
      renderItem(item);
      y += 2;
    });

    y += 5;
  };

  const renderTask = (task) => {
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(0, 0, 0);

    // Checkbox
    pdf.rect(margin, y - 3, 3.5, 3.5);
    if (task.completed) {
      pdf.setDrawColor(0);
      pdf.line(margin, y - 3, margin + 3.5, y + 0.5);
      pdf.line(margin + 3.5, y - 3, margin, y + 0.5);
    }

    // Title
    const titleX = margin + 6;
    const titleLines = pdf.splitTextToSize(task.title, contentWidth - 30);
    pdf.text(titleLines, titleX, y);

    // Duration (right aligned)
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(9);
    pdf.setTextColor(100, 100, 100);
    const dur = formatDuration(task.duration);
    pdf.text(dur, pageWidth - margin, y, { align: 'right' });

    // Badges below title
    if (task.priority || task.status || task.rolledOver) {
      y += 4;
      pdf.setFontSize(8);
      let badgeX = titleX;
      if (task.priority) {
        pdf.text(`[${task.priority}]`, badgeX, y);
        badgeX += pdf.getTextWidth(`[${task.priority}]`) + 3;
      }
      if (task.status) {
        pdf.text(`[${task.status}]`, badgeX, y);
        badgeX += pdf.getTextWidth(`[${task.status}]`) + 3;
      }
      if (task.rolledOver) {
        pdf.setTextColor(180, 100, 0);
        pdf.text('[ROLLED OVER]', badgeX, y);
        pdf.setTextColor(100, 100, 100);
      }
    }

    y += 5;
  };

  // Render each section
  addSection('⚠ Rolled Over', sections.rolledOver, renderTask);
  addSection('Open Tasks', sections.openTasks, renderTask);
  addSection('Calendar Events', sections.events, (evt) => {
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(0, 0, 0);
    const timeStr = evt.startDate
      ? evt.startDate.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })
      : '';
    pdf.text(`${timeStr ? timeStr + ' — ' : ''}${evt.title}`, margin + 6, y);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(9);
    pdf.setTextColor(100);
    pdf.text(formatDuration(evt.duration), pageWidth - margin, y, { align: 'right' });
    y += 5;
  });
  addSection('Daily Items', sections.dailyItems, renderTask);
  addSection('Weekly Items', sections.weeklyItems, renderTask);
  addSection('Monthly Items', sections.monthlyItems, renderTask);

  // Footer
  const totalPages = pdf.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(160);
    pdf.text(
      `Generated by Command Center · ${new Date().toLocaleString()} · Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pdf.internal.pageSize.getHeight() - 8,
      { align: 'center' }
    );
  }

  pdf.save(`command-center-${new Date().toISOString().slice(0, 10)}.pdf`);
}
